# Generated by Django 4.1.2 on 2022-10-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="unique_id",
            field=models.CharField(default="7B1D1A", max_length=30, unique=True),
        ),
    ]
