# Generated by Django 4.1.2 on 2022-10-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_account_unique_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="unique_id",
            field=models.CharField(default="DBF68A", max_length=30, unique=True),
        ),
    ]
